


USE PROJETS
GO

SELECT * FROM EMPLOYE

BEGIN TRANSACTION
	ALTER TABLE EMPLOYE
	ADD EMAIL varchar(100)
	INSERT INTO EMPLOYE (NO_EMPLOYE, NAS, NOM, PRENOM, SEXE, DATE_NAISSANCE, DATE_EMBAUCHE
	VALUES (1, 123456789, 'Doe', 'John', 'M', NULL, '1997-06-15', 'programmeur', 40000, NULL, NULL, NULL, NULL)
ROLLBACK